# Generated by Django 5.2.6 on 2026-02-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
