# Generated by Django 5.2.6 on 2026-03-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='diff_from_lh_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='pe_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
