# Generated by Django 5.2.6 on 2026-03-10 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dividend_investmentgoal_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('SPLIT', 'Stock Split'), ('BONUS', 'Bonus Issue'), ('DIVIDEND', 'Dividend Declared'), ('MERGER', 'Merger/Demerger')], max_length=10)),
                ('ratio_numerator', models.IntegerField(blank=True, null=True)),
                ('ratio_denominator', models.IntegerField(blank=True, null=True)),
                ('announcement_date', models.DateField()),
                ('record_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_actions', to='core.instrument')),
            ],
        ),
    ]
