# Generated by Django 5.2.6 on 2026-03-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_corporateaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='isin',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='symbol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
