# Generated by Django 5.2.6 on 2026-03-12 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_instrument_isin_alter_instrument_symbol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalNotificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_buy_count', models.IntegerField(default=0)),
                ('last_reduce_count', models.IntegerField(default=0)),
                ('last_sell_count', models.IntegerField(default=0)),
                ('last_notified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal_notification_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
