# Generated by Django 5.2.6 on 2026-03-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_signalnotificationstate_last_signals_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='previous_close',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
