# Generated by Django 5.2.6 on 2026-03-25 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_instrument_previous_close'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYearData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=9)),
                ('invested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('realized_profit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_year_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-financial_year'],
                'unique_together': {('user', 'financial_year')},
            },
        ),
    ]
