# Generated by Django 5.2.6 on 2026-03-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_financialyeardata'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyeardata',
            name='edit_count',
            field=models.IntegerField(default=0),
        ),
    ]
