# Generated by Django 5.2.6 on 2026-03-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_financialyeardata_edit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyeardata',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
